version: '3.8'

services:
  app:
    build:
      context: ./backend
    image: mariafelecan20/personal-song-journal_app:latest  
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://mariafelecan19:doamneajuta@songjournal.xogtvqh.mongodb.net/?retryWrites=true&w=majority&appName=SongJournal
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build:
      context: ./frontend 
    image: mariafelecan20/personal-song-journal_frontend:latest 
    ports:
      - "1570:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html 

volumes:
  mongo-data:
